export const AllProducts = [
  {
    id: 51,
    img: "/Folk/folk_01.jpg",
    title: "الحكايات الشعبية",
    cat: "حكايات",
    qty: 1,
    price: 50,
  },
  {
    id: 52,
    img: "/Folk/folk_02.jpg",
    title: "بابا ياجا",
    cat: "حكايات",
    qty: 1,
    price: 50,
  },
  {
    id: 53,
    img: "/Folk/folk_03.jpg",
    title: "حكايات شعبيه من مصر",
    cat: "حكايات",
    qty: 1,
    price: 50,
  },
  {
    id: 54,
    img: "/Folk/folk_04.jpg",
    title: "حكايات شعبيه عربيه",
    cat: "حكايات",
    qty: 1,
    price: 50,
  },
  {
    id: 55,
    img: "/Folk/folk_05.jpg",
    title: "من التراث الشعبي",
    cat: "حكايات",
    qty: 1,
    price: 50,
  },
  {
    id: 56,
    img: "/Folk/folk_06.jpg",
    title: "قول يا طير",
    cat: "حكايات",
    qty: 1,
    price: 50,
  },
  {
    id: 57,
    img: "/Folk/folk_07.jpg",
    title: "حكايات شعبيه مصريه",
    cat: "حكايات",
    qty: 1,
    price: 50,
  },
  {
    id: 58,
    img: "/Folk/folk_08.jpg",
    title: "حكايات شعبيه تركيه",
    cat: "حكايات",
    qty: 1,
    price: 50,
  },
  {
    id: 59,
    img: "/Folk/folk_09.jpg",
    title: "غزلان الليل",
    cat: "حكايات",
    qty: 1,
    price: 80,
  },
  {
    id: 60,
    img: "/Chlid/child_01.jpg",
    title: "لغات الحب الخمس",
    cat: "طفوله",
    qty: 1,
    price: 100,
  },
  {
    id: 61,
    img: "/Chlid/child_02.jpg",
    title: "علم نفس النمو",
    cat: "طفوله",
    qty: 1,
    price: 100,
  },
  {
    id: 62,
    img: "/Chlid/child_03.jpg",
    title: "تربيه الطفل في الاسلام",
    cat: "طفوله",
    qty: 1,
    price: 150,
  },
  {
    id: 63,
    img: "/Chlid/child_04.jpg",
    title: "سنوات الطفوله",
    cat: "طفوله",
    qty: 1,
    price: 400,
  },
  {
    id: 64,
    img: "/Chlid/child_05.jpg",
    title: "علم نفس النمو",
    cat: "طفوله",
    qty: 1,
    price: 100,
  },
  {
    id: 65,
    img: "/Chlid/child_06.jpg",
    title: "سيكولوجيه الطفوله",
    cat: "طفوله",
    qty: 1,
    price: 200,
  },
  {
    id: 66,
    img: "/Chlid/child_07.jpg",
    title: "علم نفس النمو",
    cat: "طفوله",
    qty: 1,
    price: 100,
  },
  {
    id: 67,
    img: "/Chlid/child_08.jpg",
    title: "عدوان الاطفال",
    cat: "طفوله",
    qty: 1,
    price: 100,
  },
  {
    id: 68,
    img: "/Chlid/child_09.jpg",
    title: "تعديل وبناء سلوك الاطفال",
    cat: "طفوله",
    qty: 1,
    price: 100,
  },
  {
    id: 69,
    img: "/Chlid/child_10.jpg",
    title: "سر الطفل السعيد",
    cat: "طفوله",
    qty: 1,
    price: 100,
  },
  {
    id: 70,
    img: "/Chlid/child_11.jpg",
    title: "تربيه الطفل",
    cat: "طفوله",
    qty: 1,
    price: 100,
  },
  {
    id: 71,
    img: "/Chlid/child_12.jpg",
    title: "دليل الطفل",
    cat: "طفوله",
    qty: 1,
    price: 100,
  },
  {
    id: 72,
    img: "/Islam/islam_01.jpg",
    title: "الدوله الفاطميه",
    cat: "اسلام",
    qty: 1,
    price: 279,
  },
  {
    id: 73,
    img: "/Islam/islam_02.jpg",
    title: "التاريخ الاسلامي",
    cat: "اسلام",
    qty: 1,
    price: 279,
  },
  {
    id: 74,
    img: "/Islam/islam_03.jpg",
    title: "التاريخ الاسلامي ج2",
    cat: "اسلام",
    qty: 1,
    price: 279,
  },
  {
    id: 75,
    img: "/Islam/islam_04.jpg",
    title: "بطولات من التاريخ",
    cat: "اسلام",
    qty: 1,
    price: 279,
  },
  {
    id: 76,
    img: "/Islam/islam_05.jpg",
    title: "موسوعه التاريخ",
    cat: "اسلام",
    qty: 1,
    price: 279,
  },
  {
    id: 77,
    img: "/Islam/islam_06.jpg",
    title: "من التاريخ الاسلامي",
    cat: "اسلام",
    qty: 1,
    price: 279,
  },
  {
    id: 78,
    img: "/Islam/islam_07.jpg",
    title: "قصص من التاريخ الاسلامي",
    cat: "اسلام",
    qty: 1,
    price: 279,
  },
  {
    id: 79,
    img: "/Islam/islam_08.jpg",
    title: "كتاب التاريخ الاسلامي",
    cat: "اسلام",
    qty: 1,
    price: 279,
  },
  {
    id: 80,
    img: "/Islam/islam_09.jpg",
    title: "العصر العباسي",
    cat: "اسلام",
    qty: 1,
    price: 279,
  },
  {
    id: 81,
    img: "/Islam/islam_10.jpg",
    title: "مدرسة الانبياء",
    cat: "اسلام",
    qty: 1,
    price: 279,
  },
  {
    id: 82,
    img: "/Islam/islam_11.jpg",
    title: "الاندلس",
    cat: "اسلام",
    qty: 1,
    price: 279,
  },
  {
    id: 83,
    img: "/People/people_01.jpg",
    title: "شخصيات لها تاريخ",
    cat: "شخصيات",
    qty: 1,
    price: 180,
  },
  {
    id: 84,
    img: "/People/people_02.jpg",
    title: "علم نفس المرأه",
    cat: "شخصيات",
    qty: 1,
    price: 180,
  },
  {
    id: 85,
    img: "/People/people_03.jpg",
    title: "علم الشخصية",
    cat: "شخصيات",
    qty: 1,
    price: 180,
  },
  {
    id: 86,
    img: "/People/people_04.jpg",
    title: "طبائع النساء",
    cat: "شخصيات",
    qty: 1,
    price: 180,
  },
  {
    id: 87,
    img: "/People/people_05.jpg",
    title: "تحليل الشخصيات",
    cat: "شخصيات",
    qty: 1,
    price: 180,
  },
  {
    id: 88,
    img: "/People/people_06.jpg",
    title: "ما تحت الاقنعه",
    cat: "شخصيات",
    qty: 1,
    price: 180,
  },
  {
    id: 89,
    img: "/People/people_07.jpg",
    title: "الشخصية المتكاملة",
    cat: "شخصيات",
    qty: 1,
    price: 180,
  },
  {
    id: 90,
    img: "/People/people_08.jpg",
    title: "شخصيات مثيرة للجدل",
    cat: "شخصيات",
    qty: 1,
    price: 180,
  },
  {
    id: 91,
    img: "/People/people_09.jpg",
    title: "مميز بالاصفر",
    cat: "شخصيات",
    qty: 1,
    price: 180,
  },
  {
    id: 1,
    img: "/War/war_01.jpg",
    cat: "حرب",
    qty: 1,
    title: "الحرب العالمية الاولي",
    price: 200,
  },
  {
    id: 2,
    img: "/War/war_02.jpg",
    cat: "حرب",
    qty: 1,
    title: "الحرب العالمية الثانيه",
    price: 300,
  },
  {
    id: 3,
    img: "/War/war_03.jpg",
    cat: "حرب",
    qty: 1,
    title: "الحرب عبر التاريخ",
    price: 230,
  },
  {
    id: 4,
    img: "/War/war_04.jpg",
    cat: "حرب",
    qty: 1,
    title: "الحرب من اجل الثروه ",
    price: 350,
  },
  {
    id: 6,
    img: "/War/war_06.jpg",
    cat: "حرب",
    qty: 1,
    title: "خلف خطوك العدو  ",
    price: 500,
  },
  {
    id: 7,
    img: "/War/war_07.jpg",
    cat: "حرب",
    qty: 1,
    title: "الحرب الكمياويه  ",
    price: 200,
  },
  {
    id: 8,
    img: "/War/war_08.jpg",
    cat: "حرب",
    qty: 1,
    title: "الحرب العالمية الثالثه",
    price: 400,
  },
  {
    id: 9,
    img: "/War/war_09.jpg",
    cat: "حرب",
    qty: 1,
    title: " حرب الخليج  ",
    price: 350,
  },
  {
    id: 10,
    img: "/War/war_10.jpg",
    cat: "حرب",
    qty: 1,
    title: "العقيدة العسكرية  ",
    price: 500,
  },
  {
    id: 5,
    img: "/War/war_05.jpg",
    cat: "حرب",
    qty: 1,
    title: "حروب الظل  ",
    price: 100,
  },
  {
    id: 11,
    img: "/War/war_11.jpg",
    cat: "حرب",
    qty: 1,
    title: "لماذا تنشب الحروب",
    price: 700,
  },
  {
    id: 12,
    img: "/Tech/tech_01.jpg",
    cat: "تكنولوجيا",
    qty: 1,
    title: "خدعه التكنولوجيا",
    price: 400,
  },
  {
    id: 13,
    img: "/Tech/tech_02.jpg",
    title: "دار العلم التكنولوجي",
    cat: "تكنولوجيا",
    qty: 1,
    price: 100,
  },
  {
    id: 14,
    img: "/Tech/tech_03.jpg",
    title: "الاتصال التربوي",
    cat: "تكنولوجيا",
    qty: 1,
    price: 500,
  },
  {
    id: 15,
    img: "/Tech/tech_05.jpg",
    title: " التعليم تكنولوجيا",
    cat: "تكنولوجيا",
    qty: 1,
    price: 30,
  },
  {
    id: 16,
    img: "/Tech/tech_06.jpg",
    title: "تكنولوجيا حديثه",
    cat: "تكنولوجيا",
    qty: 1,
    price: 100,
  },
  {
    id: 17,
    img: "/Tech/tech_07.jpg",
    title: "تكنولوجيا للطفال",
    cat: "تكنولوجيا",
    qty: 1,
    price: 700,
  },
  {
    id: 18,
    img: "/Tech/tech_08.jpg",
    title: "تكنولوجيا التعليم",
    cat: "تكنولوجيا",
    qty: 1,
    price: 900,
  },
  {
    id: 19,
    img: "/Tech/tech_09.jpg",
    title: "الحرب عن بعد",
    cat: "تكنولوجيا",
    qty: 1,
    price: 430,
  },
  {
    id: 20,
    img: "/Tech/tech_10.jpg",
    title: "مدخل الي تكنولوجيا التعليم",
    cat: "تكنولوجيا",
    qty: 1,
    price: 100,
  },
  {
    id: 21,
    img: "/Space/space_01.jpg",
    title: "اطلس الفضاء",
    cat: "فضاء",
    qty: 1,
    price: 100,
  },
  {
    id: 22,
    img: "/Space/space_02.jpg",
    title: "موسوعه الفضاء",
    cat: "فضاء",
    qty: 1,
    price: 700,
  },
  {
    id: 23,
    img: "/Space/space_03.jpg",
    title: "كتاب السماء",
    cat: "فضاء",
    qty: 1,
    price: 200,
  },
  {
    id: 24,
    img: "/Space/space_04.jpg",
    title: "اطلس الكون",
    cat: "فضاء",
    qty: 1,
    price: 100,
  },
  {
    id: 25,
    img: "/Space/space_05.jpg",
    title: "الفضاء والكون",
    cat: "فضاء",
    qty: 1,
    price: 900,
  },
  {
    id: 26,
    img: "/Space/space_06.jpg",
    title: "الفضاء السحيق",
    cat: "فضاء",
    qty: 1,
    price: 800,
  },
  {
    id: 27,
    img: "/Space/space_07.jpg",
    title: "علم الفلك",
    cat: "فضاء",
    qty: 1,
    price: 500,
  },
  {
    id: 28,
    img: "/Space/space_08.jpg",
    title: "عد تنازلي",
    cat: "فضاء",
    qty: 1,
    price: 100,
  },
  {
    id: 29,
    img: "/Space/space_09.jpg",
    title: "الكون والفضاء",
    cat: "فضاء",
    qty: 1,
    price: 500,
  },
  {
    id: 30,
    img: "/Space/space_10.jpg",
    title: "رائد",
    cat: "فضاء",
    qty: 1,
    price: 400,
  },
  {
    id: 31,
    img: "/Space/space_11.jpg",
    title: "فزياء الكون والفضاء",
    cat: "فضاء",
    qty: 1,
    price: 300,
  },
  {
    id: 32,
    img: "/Space/space_12.jpg",
    title: "علم الفلك",
    cat: "فضاء",
    qty: 1,
    price: 200,
  },
  {
    id: 33,
    img: "/Song/song_01.jpg",
    title: "كتاب الاغاني",
    cat: "الاغاني",
    qty: 1,
    price: 200,
  },
  {
    id: 34,
    img: "/Song/song_02.jpg",
    title: "موسوعه كتب",
    cat: "الاغاني",
    qty: 1,
    price: 200,
  },
  {
    id: 35,
    img: "/Song/song_03.jpg",
    title: "كتاب الاغاني الاصلي",
    cat: "الاغاني",
    qty: 1,
    price: 200,
  },
  {
    id: 37,
    img: "/Song/song_04.jpg",
    title: " اذاعة الاغاني جزء 1",
    cat: "الاغاني",
    qty: 1,
    price: 200,
  },
  {
    id: 38,
    img: "/Song/song_05.jpg",
    title: " اذاعة الاغاني جزء2",
    cat: "الاغاني",
    qty: 1,
    price: 200,
  },
  {
    id: 39,
    img: "/Song/song_06.jpg",
    title: "الاغاني",
    cat: "الاغاني",
    qty: 1,
    price: 100,
  },
  {
    id: 40,
    img: "/Song/song_07.jpg",
    title: "الاغاني",
    cat: "الاغاني",
    qty: 1,
    price: 200,
  },
  {
    id: 41,
    img: "/Cock/cock_01.jpg",
    title: "فنون الطبخ",
    cat: "طبيخ",
    qty: 1,
    price: 30,
  },
  {
    id: 42,
    img: "/Cock/cock_02.jpg",
    title: "كتاب الطبيخ",
    cat: "طبيخ",
    qty: 1,
    price: 70,
  },
  {
    id: 43,
    img: "/Cock/cock_03.jpg",
    title: "الطبخ الجزائري",
    cat: "طبيخ",
    qty: 1,
    price: 100,
  },
  {
    id: 44,
    img: "/Cock/cock_04.jpg",
    title: "اصول الطهي",
    cat: "طبيخ",
    qty: 1,
    price: 30,
  },
  {
    id: 45,
    img: "/Cock/cock_05.jpg",
    title: "مطبخ حواء",
    cat: "طبيخ",
    qty: 1,
    price: 75,
  },
  {
    id: 46,
    img: "/Cock/cock_06.jpg",
    title: "منال العالم",
    cat: "طبيخ",
    qty: 1,
    price: 40,
  },
  {
    id: 47,
    img: "/Cock/cock_07.jpg",
    title: "الطبيخ الميسر",
    cat: "طبيخ",
    qty: 1,
    price: 90,
  },
  {
    id: 48,
    img: "/Cock/cock_08.jpg",
    title: "الاطباق",
    cat: "طبيخ",
    qty: 1,
    price: 500,
  },
  {
    id: 50,
    img: "/Cock/cock_10.jpg",
    title: "لاله",
    cat: "طبيخ",
    qty: 1,
    price: 600,
  },
  {
    id: 49,
    img: "/Cock/cock_09.jpg",
    title: "وجبات رمضان",
    cat: "طبيخ",
    qty: 1,
    price: 100,
  },
  {
    id: 92,
    img: "/Science/science_01.jpg",
    title: "اساسيات الفزياء",
    cat: "علوم",
    qty: 1,
    price: 327,
  },
  {
    id: 93,
    img: "/Science/science_02.jpg",
    title: "فن الكمياء",
    cat: "علوم",
    qty: 1,
    price: 327,
  },
  {
    id: 94,
    img: "/Science/science_03.jpg",
    title: "اساسيات الفزياء ج2",
    cat: "علوم",
    qty: 1,
    price: 327,
  },
  {
    id: 95,
    img: "/Science/science_04.jpg",
    title: "الكمياء الحياتية",
    cat: "علوم",
    qty: 1,
    price: 327,
  },
  {
    id: 96,
    img: "/Science/science_05.jpg",
    title: "الفزياء والكمياء",
    cat: "علوم",
    qty: 1,
    price: 327,
  },
  {
    id: 97,
    img: "/Science/science_06.jpg",
    title: "نظريه التطور",
    cat: "علوم",
    qty: 1,
    price: 327,
  },
  {
    id: 98,
    img: "/Science/science_07.jpg",
    title: "قطه شرودنجر",
    cat: "علوم",
    qty: 1,
    price: 327,
  },
  {
    id: 99,
    img: "/Science/science_08.jpg",
    title: "العلوم الفزيائية",
    cat: "علوم",
    qty: 1,
    price: 327,
  },
  {
    id: 100,
    img: "/Science/science_09.jpg",
    title: "الفزياء",
    cat: "علوم",
    qty: 1,
    price: 327,
  },
  {
    id: 101,
    img: "/Science/science_10.jpg",
    title: "الكمياء الحيوية",
    cat: "علوم",
    qty: 1,
    price: 327,
  },
];
